### ISSUE TITLE
ITS GOT A TROJAN!/ VIRUS

### ISSUE THREAD

**Issue by Jaron-Wilson** [cyberofficial/TTVDropBot#20]
Microsoft

Trojan:Script/Wacatac.B!ml
Acronis (Static ML)
Please give me a clean version!

https://www.virustotal.com/gui/file/6c9e8f0f9c7eb2a48fd5f8a3b30262585d5160d01bbfde3e46dfcd0498cb71aa

**Comment by cyberofficial** [comment]
Hello, the files I provided do not have any viruses. Otherwise I wouldn't have uploaded it to github where they actively scan for malware and viruses. 

Clicking the rescan button on the virus total website also shows no viruses as that scan was 2 months ago and virus definitions do update often.

I can ensure you the file is safe to use.

**Comment by Jaron-Wilson** [comment]
Ok, thank you.

Sincerely, Jaron Wilson
